# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "demo"
app_id = "moonbit-image"
author_name = "Demo"
app_name = "Image demo (MoonBit)"

[files]
smile1 = { path = "assets/smile-1.png" }
smile2 = { path = "assets/smile-2.png" }
smile4 = { path = "assets/smile-4.png" }
