# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "demo"
app_id = "moonbit-image"
author_name = "Demo"
app_name = "Image demo (MoonBit)"

[files]
_bin = { path = "./target/wasm/release/build/image.wasm", copy = true }

# Images
"smile-1.png" = { path = "assets/smile-1.png" }
"smile-2.png" = { path = "assets/smile-2.png" }
"smile-4.png" = { path = "assets/smile-4.png" }
