# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "demo"
app_id = "moonbit-input"
author_name = "Demo"
app_name = "Input demo (MoonBit)"

[files]
_bin = { path = "./target/wasm/release/build/input.wasm", copy = true }

# Fonts
"eg_6x12.fff" = { path = "assets/eg_6x12.fff" }
