# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "demo"
app_id = "moonbit-input"
author_name = "Demo"
app_name = "Input demo (MoonBit)"

[files]
font = { path = "assets/eg_6x12.fff" }
