# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

author_id = "demo"
app_id = "moonbit-random"
author_name = "Demo"
app_name = "Random demo (MoonBit)"

[files]
_bin = { path = "./target/wasm/release/build/random.wasm", copy = true }
