# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0
name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: {} # no permissions by default

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v5

  moonbit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: ~/.moon/registry
          key: ${{ runner.os }}-moonbit-${{ hashFiles('**/moon.mod.json') }}
          restore-keys: |
            ${{ runner.os }}-moonbit-
      - uses: hustcer/setup-moonbit@66fdadf7f54f35045a7dc6357f43b1fdd1909405 # v1
      - run: moon update
      - run: task lint
      - run: task test
