# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-FileCopyrightText: 2025 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0
name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions: {} # no permissions by default

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5

  moonbit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Moonbit
        uses: actions/cache@v4
        with:
          path: ~/.moon/registry
          key: ${{ runner.os }}-moonbit-${{ hashFiles('**/moon.mod.json') }}
          restore-keys: |
            ${{ runner.os }}-moonbit-

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@e9ec6fd84ae7ee5247016223cde77038ff3cea0b # v1

      - name: Update moon package index
        run: moon update

      - name: Run tests
        run: task test

      - name: Format code
        run: task format
